apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c4ip2me0g-dotnet-basic
  janus-idp.io/tekton: c4ip2me0g-dotnet-basic
  backstage.io/kubernetes-id: c4ip2me0g-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c4ip2me0g-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
